# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e3b2226c029863c16532af888d0e46d747ae54cbbb242d8f764b1dfe507c221a0a992f3894d15b1aefb516775428bd05664414f09abccd406d3d8a640ed9c019

test:
  secret_key_base: b659704868d3b00349cc74c2ec128355e7ac259b2511128e94b64ec7acb3bfd712f206be17920e0a6a9af67434b1ad2818429b5f7580b50f4651b1828fcf777d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
